In [180]:
# label/target is categorical data here!

# 1. Navier Bayes Classifier
    a) Multinomial Naiver Bayes- targets are more than 2 in numbers
    b) Gaussian Naivier - targets are just 2 in numbers

In [181]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [182]:
from sklearn.datasets import load_iris

In [183]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [184]:
from sklearn.naive_bayes import MultinomialNB

In [185]:
iris=load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [186]:
ds=pd.DataFrame(iris.data)
ds.sample(3)

0    1    2    3
113  5.7  2.5  5.0  2.0
22   4.6  3.6  1.0  0.2
118  7.7  2.6  6.9  2.3

In [187]:
#ds1=pd.DataFrame(data='iris.data', columns ='iris.feature_names')
#ds1.sample(3)
#ERROR

In [188]:
x=iris.data
y=iris.target

In [189]:
y #there are 3 targets

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [190]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.22, random_state=43)

### MultinomialNB

In [191]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
mnb_score=accuracy_score(y_test,predmnb)
con_mat_mnb=confusion_matrix(y_test,predmnb)
class_report_mnb=classification_report(y_test,predmnb)

In [192]:
mnb_score

1.0

In [193]:
con_mat_mnb

array([[14,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  9]], dtype=int64)

In [194]:
class_report_mnb

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       1.00      1.00      1.00        10\n           2       1.00      1.00      1.00         9\n\n    accuracy                           1.00        33\n   macro avg       1.00      1.00      1.00        33\nweighted avg       1.00      1.00      1.00        33\n'

In [195]:
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.83      1.00      0.91        10
           2       1.00      0.78      0.88         9

    accuracy                           0.94        33
   macro avg       0.94      0.93      0.93        33
weighted avg       0.95      0.94      0.94        33



## 2)  K Neighbors Classifier
        from sklearn.neighbors import KNeighborsClassifier
        neigh=KNeighborsClassifier(n_neighbors=3)

In [196]:
from sklearn.neighbors import KNeighborsClassifier

In [197]:
knn=KNeighborsClassifier(n_neighbors=5) #default n=5

In [198]:
knn.fit(x_train,y_train)
knn_score=knn.score(x_train,y_train)
predknn=knn.predict(x_test)
knn_ac_score=accuracy_score(y_test,predknn)
con_mat_knn=confusion_matrix(y_test,predknn)
class_report_knn=classification_report(y_test,predknn)

In [199]:
knn_score

0.9658119658119658

In [200]:
knn_ac_score

1.0

In [201]:
print(con_mat_knn)

[[14  0  0]
 [ 0 10  0]
 [ 0  0  9]]


In [202]:
print(class_report_knn)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



## 3. Support Vector Classifier
    Provides the margin/gap betweeen two given classificattion of categorical data
    from sklearn.svm import SVC

In [203]:
from sklearn.svm import SVC

In [204]:
svc=SVC(kernel='rbf') #default value= rbf
svc.fit(x_train,y_train)
score_svc=svc.score(x_test, y_test)

In [205]:
predsvc=svc.predict(x_test)
score_ac_svc=accuracy_score(y_test,predsvc)
con_mat_svc=confusion_matrix(y_test,predsvc)
class_report_svc=classification_report(y_test,predsvc)

In [206]:
score_svc

0.9393939393939394

In [207]:
score_ac_svc 

0.9393939393939394

score and accuracy score are not same

In [208]:
con_mat_svc

array([[14,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  7]], dtype=int64)

In [209]:
print(class_report_svc)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.83      1.00      0.91        10
           2       1.00      0.78      0.88         9

    accuracy                           0.94        33
   macro avg       0.94      0.93      0.93        33
weighted avg       0.95      0.94      0.94        33



In [210]:
svc=SVC(kernel='poly') 
svc.fit(x_train,y_train)
score_svc=svc.score(x_test, y_test)
predsvc=svc.predict(x_test)
score_ac_svc=accuracy_score(y_test,predsvc)
con_mat_svc=confusion_matrix(y_test,predsvc)
class_report_svc=classification_report(y_test,predsvc)

In [211]:
print(score_ac_svc)
print(con_mat_svc)
print(class_report_svc)

1.0
[[14  0  0]
 [ 0 10  0]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



Kernel Poly is working better than kernel rbf !

In [212]:
def svmkernel(ker):
    svc=SVC(kernel=ker) 
    svc.fit(x_train,y_train)
    score_svc=svc.score(x_test, y_test)
    predsvc=svc.predict(x_test)
    score_ac_svc=accuracy_score(y_test,predsvc)
    con_mat_svc=confusion_matrix(y_test,predsvc)
    class_report_svc=classification_report(y_test,predsvc)

In [213]:
score_svc

1.0

In [214]:
svmkernel("rbf")

In [215]:
svmkernel("poly")

In [216]:
svmkernel("linear")

In [217]:
df1=pd.DataFrame(predsvc)
df1

0
0   0
1   0
2   2
3   1
4   2
5   0
6   2
7   1
8   1
9   1
10  0
11  1
12  2
13  0
14  1
15  1
16  0
17  0
18  2
19  2
20  0
21  0
22  0
23  2
24  2
25  2
26  0
27  1
28  0
29  0
30  1
31  0
32  1

In [218]:
df1.to_csv('svmkernel2.csv')

In [219]:
pd.read_csv('svmkernel2.csv')

Unnamed: 0  0
0            0  0
1            1  0
2            2  2
3            3  1
4            4  2
5            5  0
6            6  2
7            7  1
8            8  1
9            9  1
10          10  0
11          11  1
12          12  2
13          13  0
14          14  1
15          15  1
16          16  0
17          17  0
18          18  2
19          19  2
20          20  0
21          21  0
22          22  0
23          23  2
24          24  2
25          25  2
26          26  0
27          27  1
28          28  0
29          29  0
30          30  1
31          31  0
32          32  1

# Entropy (E)                                               
Randomness presrnt in the data.Only hetrogenous data are good for training models.

from sklearn.tree import DecisionTreeClassifier

# Gini Index

## 4.Decision Tree Machine classifier

In [ ]:
#ID3 algorithim

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc=DecisionTreeClassifier() # default criteria was not entropy was GINNI
dtc.fit(x_train, y_train)
score_dtc=dtc.score(x_train, y_train)
preddtc=dtc.predict(x_test)
score_ac_dtc=accuracy_score(y_test,preddtc)
con_mat_dtc=confusion_matrix(y_test, preddtc)
class_report_dtc=classification_report(y_test, preddtc)

In [ ]:
score_dtc

In [ ]:
score_ac_dtc

In [ ]:
preddtc

In [ ]:
con_mat_dtc

In [ ]:
print(class_report_dtc)

We need to check both the criteria off the decision tree classifier and must choose the best model that is of least error

We need to check all the 4 classifier of category supervision machine learning and look out for the best model that is,least error and most accurate one.

In [ ]:
print("-x-"*35)

## Saving the Best Model

In [ ]:
#mtd1 
import joblib
joblib.dump(dtc,"dtcfile.obj") #serilizartion


In [ ]:
dtc_from_joblib=joblib.load("dtcfile.obj")  #deserilization
dtc_from_joblib.predict(x_test)

In [ ]:
#2nd method
import pickle
filename="pickledtcfile.pkl"
pickle.dump(dtc,open(filename,"wb"))  #serilization

In [ ]:
load_model=pickle.load(open(filename,"rb"))  #deserilization
load_model.predict(x_test)

In [ ]:
#p=np.array([2,3,4,5,4,4])
#p.reshape(-1,1)
#dtc.predict(p)
#load_model.predict(p)

(1,-1): one row many column

# Encoding
To scale different columns data to same scale

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
y=y.reshape(-1,1)

In [ ]:
sts=StandardScaler()
z=sts.fit_transform(y)
z

In [ ]:
from sklearn.preprocessing import MinMaxScaler
stm=MinMaxScaler()
x=stm.fit_transform(x)
x

In [ ]:
trian_x
score
fit
pred
accuacy score
confuion matrix
classification report
