In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [127]:
from sklearn.datasets import load_boston

In [128]:
boston=load_boston
boston

<function sklearn.datasets._base.load_boston(*, return_X_y=False)>

In [129]:
bos=load_boston()
bos

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [130]:
bos.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [131]:
bos.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [132]:
#bos.target

In [133]:
x=bos.data

In [134]:
y=bos.target

In [135]:
check1=pd.DataFrame(bos.data)  #checking the data in boston dataset
check1.sample(3)

0     1      2    3      4      5     6       7     8      9   \
240   0.11329  30.0   4.93  0.0  0.428  6.897  54.3  6.3361   6.0  300.0   
320   0.16760   0.0   7.38  0.0  0.493  6.426  52.3  4.5404   5.0  287.0   
444  12.80230   0.0  18.10  0.0  0.740  5.854  96.6  1.8956  24.0  666.0   

       10      11     12  
240  16.6  391.25  11.38  
320  19.6  396.90   7.20  
444  20.2  240.52  23.79

### Spiliting of data for test and train purpose

In [136]:
vx_train, x_test,y_train, y_test=train_test_split(x,y,test_size=.33,random_state=47)

In [137]:
x_train.shape

(339, 13)

In [138]:
x_test.shape

(167, 13)

In [139]:
y_train.shape

(339,)

In [140]:
y_test.shape

(167,)

In [141]:
lm=LinearRegression() #using linear regression to train the model

In [142]:
lm.fit(x_train,y_train) #training the data here

LinearRegression()

In [143]:
score_lm=lm.score(x_train,y_train)
score_lm

0.7665529829880267

In [144]:
lm.coef_

array([-1.10843155e-01,  3.66995321e-02,  8.74460015e-03,  3.32218225e+00,
       -1.71846638e+01,  4.81511727e+00, -1.38022222e-02, -1.44146494e+00,
        2.63392383e-01, -1.17496784e-02, -9.25130518e-01,  9.07087108e-03,
       -4.12146398e-01])

In [145]:
bos.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [146]:
predlm=lm.predict(x_test) #we give new inputs here so that the model can predict.
predlm

array([15.84192559, 32.20569827, 24.42230605, 30.84928633, 27.31927564,
       19.65311852, 23.05432432, 31.7229619 , 32.45933432, 22.63205367,
       24.91948411, 27.15339443, 20.16729816, 27.95837435, 32.02171343,
       10.19889234, 36.05901216, 14.96179519, 11.66767994, 15.55657875,
       35.22194463, 22.20185653, 38.8142947 , 20.4290284 , 28.49163796,
       19.08044635, 24.02797912, 20.78907881, 19.65030776, 26.41697272,
       14.14117934, 25.89121978, 17.77544803,  8.02793933, 32.83228276,
       19.02926719, 12.35104367, 27.13926668, 22.64549403, 18.75190375,
       23.67614267, 25.19654715, 37.31343761, 21.2740326 , 32.30876439,
       20.32537386,  7.41789113, 28.06144027, 36.28142462, 21.53339694,
       28.92419026, 23.82647841,  7.34739041, 24.23067937,  6.12843722,
       21.90316166, 18.29285279, 13.19056989,  5.99004693, 30.08061674,
       12.37541899, 17.83046748, 18.15297944, 19.08005857, 42.19993227,
       22.50076808, 20.52857282, 23.9328331 , 25.64429237, 27.51

##### Calculating Mean Square Error

In [147]:
mse_lm=mean_squared_error(y_test,predlm) 
mse_lm

27.42072820908458

In [148]:
np.sqrt(mse_lm)

5.236480517397594

### As the errors are existing there may be case that model is going through under fitting or overfitting.

In [149]:
print("-x-"*42)

-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-


# Regularization :: L1 & L2
        L1- lasso regression
        L2-ridge regression
        Elastic Net regression

Alpha value remains same in each regression for comparison and understanding.

In [150]:
from sklearn.linear_model import Lasso,Ridge

#### L1 Lasso Regression

In [151]:
ls=Lasso(alpha=0.0001)
ls.fit(x_train,y_train)     #training through lasso #we train the data here
#lm.fit(x_train,y_train)    #training through linear regression

Lasso(alpha=0.0001)

In [152]:
score_ls=ls.score(x_train, y_train) #score through lasso
score_ls
#score_lm = 0.7665529829880267     #score through linear regression

0.7665529400345414

In [153]:
predlasso=ls.predict(x_test)
predlasso

array([15.84606573, 32.20576863, 24.41981132, 30.85017427, 27.31949877,
       19.65382971, 23.05598908, 31.72472312, 32.45700698, 22.62901443,
       24.92040181, 27.155101  , 20.16578767, 27.95515696, 32.01750512,
       10.19972762, 36.0574698 , 14.96231357, 11.66832743, 15.55780401,
       35.22049777, 22.20015392, 38.8138701 , 20.4272614 , 28.48947487,
       19.0769333 , 24.02675867, 20.79107988, 19.6521658 , 26.41596573,
       14.14194211, 25.8889935 , 17.77395953,  8.02834456, 32.82931039,
       19.03173187, 12.35189452, 27.14017292, 22.64526427, 18.75440132,
       23.67798789, 25.19665611, 37.31143289, 21.2741172 , 32.3074552 ,
       20.32348215,  7.41531104, 28.06024871, 36.28278154, 21.53693776,
       28.92236519, 23.82610102,  7.34841474, 24.23130114,  6.12735844,
       21.90499905, 18.29338587, 13.1911147 ,  5.99030651, 30.0798539 ,
       12.37666362, 17.82653755, 18.15199713, 19.0807606 , 42.19882326,
       22.50010063, 20.52777688, 23.93023915, 25.64334323, 27.51

In [154]:
mse_lasso=mean_squared_error(y_test,predlasso) #mean square error with lasso
mse_lasso
#27.42072820908458 = mse_lm

27.420686040715154

In [155]:
np.sqrt(mse_lasso) 

5.236476490992311

Error should be reduced, this is our agenda here!

### Difference % between the mean squares of linear and lasso

In [156]:
per=((mse_lm - mse_lasso)/mse_lm)*100
print(per,"% model has been imporved")

0.0001537828211711744 % model has been imporved


In [174]:
print("-x-"*42)

-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-


#### L2 Ridge Regression

In [157]:
rd=Ridge(alpha=0.0001)

In [158]:
rd.fit(x_train, y_train)

Ridge(alpha=0.0001)

In [159]:
score_rd=rd.score(x_train, y_train)
score_rd

0.7665529828886578

In [160]:
predridge=rd.predict(x_test)

In [161]:
mse_rd=mean_squared_error(y_test, predridge)
mse_rd

27.420755562391207

In [162]:
np.sqrt(mse_rd)

5.236483129199521

In [163]:
#min_error=min(mse_rd,mse_lasso, mse_lm)
#min_error

In [164]:
rd.coef_

array([-1.10842268e-01,  3.66998800e-02,  8.73686616e-03,  3.32215005e+00,
       -1.71830063e+01,  4.81513570e+00, -1.38038984e-02, -1.44144307e+00,
        2.63388003e-01, -1.17498140e-02, -9.25109364e-01,  9.07099128e-03,
       -4.12146425e-01])

In [165]:
per2=((mse_lasso - mse_rd)/mse_lasso)*100
print(per2,"% model has been imporved")

-0.00025353733291031864 % model has been imporved


Lasso method was better than ridge regresson in this case!

In [166]:
per3=((mse_lm - mse_rd)/mse_lm)*100
print(per3,"% model has been imporved")

-9.975412184228098e-05 % model has been imporved


Linear regression was much bettter than ridge in this case!

In [175]:
print("-x-"*42)

-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-


### Elastic Net Regression

In [167]:
from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.0001)

In [168]:
enr.fit(x_train, y_train) #we have trained it

ElasticNet(alpha=0.0001)

In [169]:
score_enr=enr.score(x_train, y_train) #we have checked the accuracy of training
score_enr

0.7665498739655396

In [170]:
enrpred=enr.predict(x_test) #we have predicted some values
#enrpred

In [171]:
mse_enr=mean_squared_error(y_test, enrpred) #we have checked the error
mse_enr

27.425497789971285

In [172]:
np.sqrt(mse_enr)

5.23693591616045

In [173]:
per4=((mse_lasso - mse_enr)/mse_lasso)*100  #now at the end, compared the error
print(per4,"% model has been imporved")

-0.017547880636488784 % model has been imporved


### Lasso is the best in this case!

In [176]:
print("-x-"*42)

-x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x--x-
